default_platform(:ios)

platform :ios do
  before_all do
    setup_ci if ENV["CI"]
  end

  desc "Build & upload to TestFlight (no auto-submission)"
  lane :beta do
    match(type: "appstore", readonly: ENV["CI"] ? true : false)

    increment_build_number(
      build_number: number_of_commits,
      xcodeproj: Dir["*.xcodeproj"].first
    )

    build_app(
      scheme: "<SCHEME>",
      export_method: "app-store",
      output_directory: "./build",
      clean: true
    )

    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_CONTENT"],
      is_key_content_base64: true,
      in_house: false
    )

    pilot(
      api_key: api_key,
      skip_waiting_for_build_processing: true,
      skip_submission: true,
      distribute_external: false
    )
  end
end
